### ISSUE TITLE
User is unable to cast a vote using the POST /api/vote EP

### ISSUE THREAD

**Issue by mainangethe** [chingu-voyages/v24-bears-team-04-be#21]
**Description**
When I send a candidate's name to the EP, I am getting a Test Name with 0 votes every time with a successful 200 OK status.

**Expected Result**
The EP should return my candidate's name & increase his/her vote by 1 every time I vote.

**Actual Result**
Get same result, `_id: 1, Name: Test Name, Votes: 0`

**Steps To Recreate**
1. Use `mychoice-api.herokuapp.com` as the base_url
2. Enter EP: `/api/vote` with the `POST` method
3. Add a `candidate_name` key:value pair in the body as JSON 
```json
{ 
    "candidate_name": "John McCain"
}
```
4. Send the request
5. View results

**Screenshot**
![BUG_unable_to_cast_vote_062121102020.png](https://images.zenhubusercontent.com/5d42d17b36adaa5bbc60b92d/d2ba8c73-5af5-4c51-93dc-0c5056868da1)

**Comment by sophyphreak** [comment]
Huh, weird. Let me look at it...

**Comment by sophyphreak** [comment]
I have a working endpoint at https://secret-temple-85527.herokuapp.com/api/vote My guess is that you need to pull `main` before pushing to heroku. That's was the returned value of the backend POST command earlier today.

**Comment by mainangethe** [comment]
Issue resolved: Problem was "https://" was missing from the end point.

We need to use the full secure url to POST votes
